# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: CV
    url: uploads/resume.pdf
    weight: 20
  #- name: Posts
  #  url: '#posts'
  #  weight: 30
  # - name: Projects
  #  url: '#projects'
  #  weight: 40
  # - name: Talks
  #  url: '#talks'
  #  weight: 50
  - name: Publications
    url: '#papers'
    weight: 30
  - name: Contact
    url: '#contact'
    weight: 50
  - name: Teaching
    identifier: courses
    url: '#courses'
    weight: 40
  - name: Microeconomia I
    parent: courses
    url: teaching/micro
    weight: 10
  - name: Macroeconomia I
    parent: courses
    url: teaching/macro
    weight: 20
  - name: Métodos Quantitativos I
    parent: courses
    url: teaching/metodosquant
    weight: 30
  #- name: Pensamento Contemporâneo
  #  parent: courses
  #  url: teaching/pec
  #  weight: 40